# Generated by Django 4.2.10 on 2024-05-06 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newslettermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettermodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
