# Generated by Django 4.2.10 on 2024-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newslettermodel_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
