# Generated by Django 4.2.10 on 2024-04-22 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount_pecent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
