# Generated by Django 4.2.10 on 2024-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_wishlistproductmodelok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistProductModelOK',
        ),
    ]
