# Generated by Django 4.2.10 on 2024-05-07 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddresModel',
            new_name='UserAddressModel',
        ),
    ]
