# Generated by Django 4.2.10 on 2024-05-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_useraddresmodel_useraddressmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='addres',
            new_name='address',
        ),
    ]
