# Generated by Django 4.2.10 on 2024-05-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_couponmodel_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='order.couponmodel'),
        ),
    ]
