# Generated by Django 4.2.10 on 2024-05-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
