# Generated by Django 4.2.10 on 2024-05-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
